### PR TITLE
completely replaced gray textures with regular item render

### PR DESCRIPTION
**Pull request by HiWord9**
now u dont need to use gray textures and mod authors dont need to draw same gray texture for ur mod, ghost item now rendered as regular. And a few little changes

### CODE REVIEW

**Comment by HiWord9** [comment]
showcase
And completely removed button that shows how items looks like

**Comment by HiWord9** [comment]
+ added ability to move items to other slots in SpecificGui when they are already placed, and ability to remove them if u move them off inventory

**Comment by HiWord9** [comment]
i haven't changed any translations insteed of english if anything

**Comment by LopyMine** [comment]
I don’t really like this solution, the gray textures style was taken from Minecraft, but here you have visual items under which there is some color panel, and everything still has the feeling of an item in the inventory

**Comment by LopyMine** [comment]
This is also very confusing

**Comment by HiWord9** [comment]
image
gotcha bro 😎

**Comment by LopyMine** [comment]
Looks good, thanks!

**Pull request merged**
